<form action="<?= route('areas.update', ['id' => $area->id]) ?>" method="POST" class="<?= $area->hasErrors() ? '' : 'was-validated' ?>" novalidate>
    <input type="hidden" name="_method" value="PUT">
    <div class="mb-3">
        <label for="area_title" class="form-label">Título:</label>
        <input type="text" name="area[title]" class="form-control" id="area_title" value="<?= $area->title ?>" required>
        <div class="invalid-feedback"><?= $area->errors('title') ? $area->errors('title') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_zipcode" class="form-label">CEP:</label>
        <input type="text" name="area[zipcode]" class="form-control" id="area_zipcode" value="<?= $area->zipcode ?>" required>
        <div class="invalid-feedback"><?= $area->errors('zipcode') ? $area->errors('zipcode') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_street" class="form-label">Rua:</label>
        <input type="text" name="area[street]" class="form-control" id="area_street" value="<?= $area->street ?>" required>
        <div class="invalid-feedback"><?= $area->errors('street') ? $area->errors('street') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_city" class="form-label">Cidade:</label>
        <input type="text" name="area[city]" class="form-control" id="area_city" value="<?= $area->city ?>" required>
        <div class="invalid-feedback"><?= $area->errors('city') ? $area->errors('city') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_state" class="form-label">Estado:</label>
        <input type="text" name="area[state]" class="form-control" id="area_state" value="<?= $area->state ?>" required>
        <div class="invalid-feedback"><?= $area->errors('state') ? $area->errors('state') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_number" class="form-label">Número:</label>
        <input type="text" name="area[number]" class="form-control" id="area_number" value="<?= $area->number ?>" required>
        <div class="invalid-feedback"><?= $area->errors('number') ? $area->errors('number') : '' ?></div>
    </div>
    <button type="submit" class="btn btn-primary">Atualizar</button>
</form>