<form action="<?= route('areas.create') ?>" method="POST" class="<?= $area->hasErrors() ? '' : 'was-validated' ?>" novalidate enctype="multipart/form-data">
    <div class="mb-3">
        <label for="area_title" class="form-label">Título:</label>
        <input type="text" value="<?= $area->title ?>" name="area[title]" class="form-control" id="area_title" required>
        <div class="invalid-feedback"><?= $area->errors('title') ? $area->errors('title') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_zipcode" class="form-label">CEP:</label>
        <input type="text" value="<?= $area->zipcode ?>" name="area[zipcode]" class="form-control" id="area_zipcode" required>
        <div class="invalid-feedback"><?= $area->errors('zipcode') ? $area->errors('zipcode') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_street" class="form-label">Rua:</label>
        <input type="text" value="<?= $area->street ?>" name="area[street]" class="form-control" id="area_street" required>
        <div class="invalid-feedback"><?= $area->errors('street') ? $area->errors('street') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_city" class="form-label">Cidade:</label>
        <input type="text" value="<?= $area->city ?>" name="area[city]" class="form-control" id="area_city" required>
        <div class="invalid-feedback"><?= $area->errors('city') ? $area->errors('city') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_state" class="form-label">Estado:</label>
        <input type="text" value="<?= $area->state ?>" name="area[state]" class="form-control" id="area_state" required>
        <div class="invalid-feedback"><?= $area->errors('state') ? $area->errors('state') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_number" class="form-label">Número:</label>
        <input type="text" value="<?= $area->number ?>" name="area[number]" class="form-control" id="area_number" required>
        <div class="invalid-feedback"><?= $area->errors('number') ? $area->errors('number') : '' ?></div>
    </div>
    <div class="mb-3">
        <label for="area_image" class="form-label">Imagem:</label>
        <input type="file" name="area_image" class="form-control" id="areaImage" required>
        <img id="imagePreview" src="#" alt="Pré-visualização da imagem" style="display: none; max-width: 100%; margin-top: 10px;">
    </div>
    <button type="submit" class="btn btn-primary">Registrar</button>
</form>

<div class="modal fade" id="previewModal" tabindex="-1" aria-labelledby="previewModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="previewModalLabel">Pré-visualização da Imagem</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img id="imagePreviewModal" src="#" alt="Pré-visualização da imagem" style="max-width: 100%;">
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary d-none" id="selectImage">Selecionar essa imagem</button>
            </div>
        </div>
    </div>
</div>

<script src="/assets/js/areas/imagePreview.js"></script>