<div class="text-center">
    <div>
        <img id="image_preview" class="avatar rounded-circle img-thumbnail" src="<?= $this->current_user->avatar()->path() ?>" alt="avatar">

        <form action="<?= route('profile.avatar') ?>" method="POST" enctype="multipart/form-data">
            <label for="image_preview_input" class="btn btn-fill btn-light mt-2 me-2">Alterar Imagem</label>
            <input id="image_preview_input" class="d-none" type="file" name="user_avatar" id="user_avatar">
            <button id="image_preview_submit" type="submit" class="btn btn-fill btn-outline-primary d-none mt-2">Atualizar</button>
        </form>

    </div>
    <div class="col-12 d-flex justify-content-center">
        <form action="<?= route('profile.update') ?>" class="col-12 text-start" method="POST" style="max-width: 400px;">
            <div class="form-group mt-2">
                <label for="user_name">Nome</label>
                <input type="text" name="user_name" value="<?= $this->current_user->name ?>" class="form-control">
            </div>
            <div class="form-group mt-2">
                <label for="user_email">Email</label>
                <input type="email" name="user_email" value="<?= $this->current_user->email ?>" class="form-control">
            </div>
            <div class="form-group mt-2">
                <label for="user_password">Senha</label>
                <input type="password" name="user_password" class="form-control">
            </div>
            <div class="form-group mt-2">
                <label for="user_password_confirmation">Confirmação de Senha</label>
                <input type="password" name="user_password_confirmation" class="form-control">
            </div>
            <div class="col-12 text-end mt-3">
                <button type="submit" class="btn btn-primary mt-2">Salvar</button>
            </div>
        </form>
    </div>
</div>