<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rastreador de Areas</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jura:wght@300..700&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="/assets/css/application.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= route('root') ?>"><img src="/assets/images/join-ecology-logo.png" alt="Logo Join" style="max-width: 80px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <?php if ($this->current_user) : ?>
                        <?php if (!$this->current_user->isAdmin()) : ?>
                            <li class="nav-item">
                                <a href="<?= route('areas.new') ?>" class="nav-link">
                                    <i class="fe fe-plus"></i>Cadastrar Area
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= route('areas.index') ?>">Minhas areas</a>
                            </li>
                        <?php endif; ?>
                        <?php if ($this->current_user->isAdmin()) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= route('reinforce.areas') ?>">Todas as Areas</a>
                            </li>
                        <?php endif; ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= route('profile.show') ?>">Opções da Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= route('users.logout') ?>">Sair</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
    
    <main class="container-fluid">
        <div class="row">
            <section id="main-content" class="col">
                <div class="container">                
                    <?php require '_flash_message.phtml'; ?>
                    
                    <header class="mb-3">
                        <h1>
                            <?= $title ?>
                        </h1>
                    </header>
                    
                    <?php require $view ?>
                </div>

            </section>
        </div>
    </main>
</body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="/assets/js/application.js"></script>
    <script src="/assets/js/utils.js"></script>
</html>